### ISSUE TITLE
Support Python 3.11 in python client

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#1103]
### Body

Currenly, our [python client](https://github.com/apache/streampipes/tree/dev/streampipes-client-python) does not support running on Python `3.11`. This is mainly due to the missing compatibility of our dependency `nats-py` (as of version `2.2.0`).

### ToDos

- [ ] make client Python `3.11` ready
- [ ] add `3.11` tag to `setup.py` 
- [x] include `3.11` in pr validation workflow

### Mentoring
As this ticket is marked as good first issue: @bossenti is happy to provide help for getting started.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by yash013** [comment]
hello there, 
I am new to open source I want to work on this issue. pls tell me how to get started

**Comment by bossenti** [comment]
Great that you found your way to StreamPipes @yash013 🎉 
I'm afraid this issue is not ready to work on as `nats-py` (one of our dependencies) is not yet supporting `3.11` 🙁

**Comment by yash013** [comment]
okay. no problem. do you have any other issue on which I should work on.

**Comment by bossenti** [comment]
Sure, we have plenty of good first issues: https://github.com/apache/streampipes/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

Just browse them and choose one that fits you best
