### ISSUE TITLE
Streamline domain property usage

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#1373]
### Body

Although, we have a dedicated [vocubalury ](https://github.com/apache/streampipes/tree/dev/streampipes-vocabulary) that provides extensive definitions of several [domain properties](https://streampipes.apache.org/docs/docs/extend-sdk-stream-requirements.html#specifying-semantics) and other stuff, we have plenty of places in our code where we still have hard coded domain properties. One example can be found [here](https://github.com/apache/streampipes/blob/dev/streampipes-extensions/streampipes-processors-geo-jvm/src/main/java/org/apache/streampipes/processors/geo/jvm/jts/processor/epsg/EpsgProcessor.java#L55).

### Tasks

- [ ] collect hard-coded domain properties
- [ ] extend (and rework) vocabulayry
- [ ] replace hard-coded domain properties by vocabulary
- [ ] (extend vocabulary by common runtime names, see https://github.com/apache/streampipes/discussions/1265) 

### Mentoring
As this issue is marked as good first issue: one of @dominikriemer, @tenthe, or @bossenti are happy to provide help for getting started, just tag (one of) them if you want to start working on this issue and need some help.
This issue is ideal for people that are interested in getting started with StreamPipes and its SDK.

Related: https://github.com/apache/streampipes/discussions/1312

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by zand951** [comment]
@bossenti, can I work on this. Since this is my very first open source project I just want to clarify what exactly I need to do for task 1, please bare with me :). 

So, for task 1 I just need to scan through all files @ https://github.com/apache/streampipes and search for .domainProperty("foo") right?

**Comment by zand951** [comment]
Hi, could you provide me with the permission to push to a new branch please?

**Comment by zand951** [comment]
Task 1 for Streamline domain property usage #1373

Below is the location where hardcoded .domainProperty or .domainPropertyReq is found. 

C:\Users\Andyz\streampipes\streampipes-extensions\streampipes-processors-geo-jvm\src\main\java\org\apache\streampipes\processors\geo\jvm\jts\processor\buffergeometry\BufferGeomProcessor.java

C:\Users\Andyz\streampipes\streampipes-extensions\streampipes-processors-geo-jvm\src\main\java\org\apache\streampipes\processors\geo\jvm\jts\processor\bufferpoint\BufferPointProcessor.java

C:\Users\Andyz\streampipes\streampipes-extensions\streampipes-processors-geo-jvm\src\main\java\org\apache\streampipes\processors\geo\jvm\jts\processor\epsg\EpsgProcessor.java

C:\Users\Andyz\streampipes\streampipes-extensions\streampipes-processors-geo-jvm\src\main\java\org\apache\streampipes\processors\geo\jvm\jts\processor\latlngtojtspoint\LatLngToJtsPointProcessor.java

C:\Users\Andyz\streampipes\streampipes-extensions\streampipes-processors-geo-jvm\src\main\java\org\apache\streampipes\processors\geo\jvm\jts\processor\reprojection\ReprojectionProcessor.java

C:\Users\Andyz\streampipes\streampipes-extensions\streampipes-processors-geo-jvm\src\main\java\org\apache\streampipes\processors\geo\jvm\jts\processor\trajectory\TrajectoryFromPointsProcessor.java

C:\Users\Andyz\streampipes\streampipes-extensions\streampipes-processors-image-processing-jvm\src\main\java\org\apache\streampipes\processors\imageprocessing\jvm\processor\commons\RequiredBoxStream.java

C:\Users\Andyz\streampipes\streampipes-extensions\streampipes-processors-image-processing-jvm\src\main\java\org\apache\streampipes\processors\imageprocessing\jvm\processor\genericclassification\GenericImageClassificationProcessor.java

C:\Users\Andyz\streampipes\streampipes-extensions\streampipes-processors-image-processing-jvm\src\main\java\org\apache\streampipes\processors\imageprocessing\jvm\processor\qrreader\QrCodeReaderProcessor.java

C:\Users\Andyz\streampipes\ui\src\app\dashboard\sdk\ep-requirements.ts

**Comment by flomickl** [comment]
all domainProperties in geo-jvm are linked to this discussion #1312 and would be good to be handled separately I guess

**Comment by bossenti** [comment]
@zand951 welcome to StreamPipes 🙌 
Great to hear that you are interested in contributing!

> Since this is my very first open source project I just want to clarify what exactly I need to do for task 1, please bare with me :).

Sure, feel free to reach out whenever you have any question 🙂

**Comment by bossenti** [comment]
> could you provide me with the permission to push to a new branch please?

Unfortunately not
The standard proactively that is common for the vast majority of open source projects is that you create a fork of your target (in this case StreamPipes) and then creates PR from your fork to our repo
Here are some more information on how to do that: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by bossenti** [comment]
> all domainProperties in geo-jvm are linked to this discussion #1312 and would be good to be handled separately I guess

@flomickl why do you think so? 
From my point of view the discussion is closed and we can start working on it
Happy to hear your thoughts 🙂

**Comment by flomickl** [comment]
just want to mention that this is geo vocabulary 
and that there are more vocabularies in the backhand /mentioned in the discussion)  and is part of the extent vocabulary

**Comment by Jayyadav1903** [comment]
Hi @bossenti, @tenthe 
I’m interested in working on this issue and would like to start with a very limited scope contribution to avoid any unintended refactoring.
My proposal is to only tackle Task 1 initially:
systematically collect and document remaining hard-coded domain property usages across the codebase
without changing behavior, vocabulary structure, or runtime logic
Happy to align with any preferred approach or guidance before starting. Thanks!
