### ISSUE TITLE
Migration to New Data Processor API

### ISSUE THREAD

**Issue by tenthe** [apache/streampipes#3200]
### Body

#Description

Currently, we support two options for implementing processing elements:

- **Recommended**: `IStreamPipesDataProcessor` (interface)
- **Legacy**: `StreamPipesDataProcessor` (abstract class)

Most internal processors still rely on the legacy `StreamPipesDataProcessor` class.

## Tasks

- [ ] Migrate the `StreamPipesDataProcessor` class to the new API (`IStreamPipesDataProcessor`).
- [ ] Migrate all processing elements to the new API.
- [ ] Remove the deprecated `StreamPipesDataProcessor` class after one release.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.
