### ISSUE TITLE
Migrate remaining Jenkins job to GitHub actions

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#843]
### Body

Currently, we still use Jenkins to deploy our Snapshot version to Maven on a daily/nightly (?) basis.
We should migrate this workflow as well to GitHub actions to have everything in one place.
The job description can be found [here](https://github.com/apache/streampipes/blob/dev/Jenkinsfile).

### ToDos

- [ ] create ticket at INFRA to add secrets `NEXUS_USER` and `NEXUS_PW ` to our repository
- [ ] build the snapshot deployemt as a scheduled GitHub actions workflow

### Related:
- https://issues.apache.org/jira/browse/INFRA-23810

### Mentoring
As this ticket is marked as `good first issue`: @tenthe, @dominikriemer or @bossenti are happy to provide for getting started and especially to support with regard to the communication with INFRA since this needs to be done from the core team.

### StreamPipes Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.
